CREATE INDEX BANK_QUERY ON BANK_TRANSACTION("DATE", WITHDRAWAL_AMT);
/* SQL QUERY TO FIND LOWEST AMOUNT DEBITED FROM THE BANK IN EACH YEAR */

SELECT TO_NUMBER(MIN(WITHDRAWAL_AMT)) AS MINIMUM_WITHDRAWAL_AMT,
EXTRACT(YEAR FROM "DATE") AS YEAR
FROM BANK_TRANSACTION
GROUP BY EXTRACT(YEAR FROM "DATE") 
ORDER BY EXTRACT(YEAR FROM "DATE"); 

/* SQL QUERY TO FIND THE FIRST FIVE LARGEST WITHDRAWAL TRANSACTIONS OCCURED IN THE YEAR 2018 */

SELECT TO_NUMBER(REPLACE(WITHDRAWAL_AMT,'"','')) AS FIRST_FIVE_HIGHEST_DEPOSITED_AMOUNT_IN_2018
FROM BANK_TRANSACTION WHERE WITHDRAWAL_AMT IS NOT NULL 
AND EXTRACT(YEAR FROM "DATE")=2018
AND REGEXP_LIKE(REPLACE(WITHDRAWAL_AMT,' ',''), '^[0-9]+(\.[0-9]+)?$')
ORDER BY TO_NUMBER(REPLACE(WITHDRAWAL_AMT,'"','')) DESC 
OFFSET 0 ROWS FETCH NEXT 5 ROWS ONLY;

/* SQL QUERY TO COUNT THE WITHDRAWAL TRANSACTIONS BETWEEN MAY 5,2018 AND MAR 7,2019 */
SELECT COUNT(WITHDRAWAL_AMT) FROM BANK_TRANSACTION 
WHERE "DATE" BETWEEN '05-MAY-18' AND '07-MAR-19'
AND WITHDRAWAL_AMT IS NOT NULL; 

/* SQL QUERY TO FIND HIGHEST AMOUNT DEBITED FROM THE BANK IN EACH YEAR */ 

SELECT MAX(TO_NUMBER(REPLACE(WITHDRAWAL_AMT,'"',''))) AS LARGEST_DEPOSITED_AMOUNT_IN_A_YEAR,
EXTRACT(YEAR FROM "DATE") AS YEAR
FROM BANK_TRANSACTION WHERE WITHDRAWAL_AMT IS NOT NULL
AND REGEXP_LIKE(REPLACE(WITHDRAWAL_AMT,' ',''), '^[0-9]+(\.[0-9]+)?$')
GROUP BY EXTRACT(YEAR FROM "DATE")
ORDER BY EXTRACT(YEAR FROM "DATE");