/* QUERY TO FIND HIGHEST AMOUNT DEBITED EACH YEAR */

SELECT EXTRACT(YEAR FROM "DATE") AS YEAR,
MAX(CAST(WITHDRAWAL_AMT AS NUMBER(10,2)DEFAULT NULL ON CONVERSION ERROR)) AS highest_debited_amount FROM BANK_TRANSACTION
GROUP BY EXTRACT(YEAR FROM "DATE")
ORDER BY YEAR;