/* QUERY TO FIND HIGHEST AMOUNT DEBITED EACH YEAR */

SELECT EXTRACT(YEAR FROM "DATE") AS YEAR,
MAX(CAST(WITHDRAWAL_AMT AS NUMBER(10,2)DEFAULT NULL ON CONVERSION ERROR)) AS highest_debited_amount FROM BANK_TRANSACTION
GROUP BY EXTRACT(YEAR FROM "DATE")
ORDER BY YEAR;

/* QUERY TO FIND LOWEST AMOUNT DEBITED EACH YEAR */

SELECT EXTRACT(YEAR FROM "DATE") AS YEAR,
Min(CAST(WITHDRAWAL_AMT AS NUMBER(10,2)DEFAULT NULL ON CONVERSION ERROR)) AS lowest_debited_amount FROM BANK_TRANSACTION
GROUP BY EXTRACT(YEAR FROM "DATE")
ORDER BY YEAR;

/* QUERY TO FIND COUNT THE WITHDRAWAL TRANSACTION BETWEEN 5-MAY-2018 AND 7-MAR-2019 */
SELECT COUNT(*) AS WITHDRAWAL_COUNT FROM BANK_TRANSACTION
WHERE "DATE" >= TO_DATE('05-MAY-18','DD-MON-YY')
AND "DATE" <= TO_DATE('07-MAR-19','DD-MON-YY')
AND WITHDRAWAL_AMT IS NOT NULL;